-- AlterTable
ALTER TABLE `memoboard` ADD COLUMN `index` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ALTER COLUMN `background` DROP DEFAULT;
